### ISSUE TITLE
ValueError: Required property 'conversation_id' not present in Context JSON

### ISSUE THREAD

**Issue by dhoffmann1979** [IBM/watson-online-store#134]
I have installed everything from the Garage Tutorial. On the first Message send from Slack, the error appears.

Here is the full message:
`Traceback (most recent call last):
  File "run.py", line 189, in <module>
    watsononlinestore.run()
  File "/Users/daniel/Ohne Sync/watson-online-store-test/watsononlinestore/watson_online_store.py", line 859, in run
    self.handle_conversation(message, sender, user)
  File "/Users/daniel/Ohne Sync/watson-online-store-test/watsononlinestore/watson_online_store.py", line 835, in handle_conversation
    get_input = self.handle_message(message, sender)
  File "/Users/daniel/Ohne Sync/watson-online-store-test/watsononlinestore/watson_online_store.py", line 796, in handle_message
    watson_response = self.get_watson_response(message)
  File "/Users/daniel/Ohne Sync/watson-online-store-test/watsononlinestore/watson_online_store.py", line 509, in get_watson_response
    context=self.context)
  File "/usr/local/lib/python2.7/site-packages/watson_developer_cloud/conversation_v1.py", line 310, in message
    context = self._convert_model(context, Context)
  File "/usr/local/lib/python2.7/site-packages/watson_developer_cloud/watson_service.py", line 253, in _convert_model
    val = classname._from_dict(dict(val))
  File "/usr/local/lib/python2.7/site-packages/watson_developer_cloud/conversation_v1.py", line 1716, in _from_dict
    'Required property \'conversation_id\' not present in Context JSON'
ValueError: Required property 'conversation_id' not present in Context JSON`

**Comment by scottdangelo** [comment]
I've reproduced this bug.

I've pushed up the branch `Bug134MissingConversation_id`:

Here I've added lots of debug code.
In WatsonOnlineStore __init__ I've sent an empty message, to
initialize the conversation with a conversation_id.
This gets returned in the context, which is later sent at
the point of failure.
But it still fails.


Here we have the `conversation_id` in the context for the message that is being sent, yet we still get the Exception:
```
WARNING:watsononlinestore.watson_online_store:inputhi
WARNING:watsononlinestore.watson_online_store:context:
WARNING:watsononlinestore.watson_online_store:{'intents': [], 'entities': [], 'input': {}, 'output': {'text': ['Hello! and Welcome to Watson Online Store.'], 'nodes_visited': ['Welcome'], 'log_messages': []}, 'context': {'conversation_id': 'c1dfce32-3e10-446a-8bd5-8455f8ebe24e', 'system': {'dialog_stack': [{'dialog_node': 'Welcome'}], 'dialog_turn_counter': 1, 'dialog_request_counter': 1, '_node_output_map': {'Welcome': [0]}}, 'get_input': 'yes', 'input_text': '', 'shopping_cart': 'list'}, 'type': 'customer', 'email': 'scott.dangelo@ibm.com', 'first_name': 'Scott', 'last_name': 'DAngelo', 'shopping_cart': []}
Traceback (most recent call last):
  File "run.py", line 189, in <module>
    watsononlinestore.run()
 File "/Users/scottda/GitRepos/DevJourneys/watson-online-store/watsononlinestore/watson_online_store.py", line 878, in run
    self.handle_conversation(message, sender, user)
  File "/Users/scottda/GitRepos/DevJourneys/watson-online-store/watsononlinestore/watson_online_store.py", line 854, in handle_conversation
    get_input = self.handle_message(message, sender)
  File "/Users/scottda/GitRepos/DevJourneys/watson-online-store/watsononlinestore/watson_online_store.py", line 813, in handle_message
    watson_response = self.get_watson_response(message)
  File "/Users/scottda/GitRepos/DevJourneys/watson-online-store/watsononlinestore/watson_online_store.py", line 526, in get_watson_response
    context=self.context)
  File "/Users/scottda/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/conversation_v1.py", line 310, in message
    context = self._convert_model(context, Context)
  File "/Users/scottda/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/watson_service.py", line 253, in _convert_model
    val = classname._from_dict(dict(val))
  File "/Users/scottda/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/conversation_v1.py", line 1716, in _from_dict
    'Required property \'conversation_id\' not present in Context JSON'
ValueError: Required property 'conversation_id' not present in Context JSON
```

**Comment by scottdangelo** [comment]
Note: you need to scroll the message above to get all the context...line is too long.

**Comment by scottdangelo** [comment]
Better version of the context:
```
{
    "intents": [],
    "entities": [],
    "input": {},
    "output": {
        "text": [
            "Hello! and Welcome to Watson Online Store."
        ],
        "nodes_visited": [
            "Welcome"
        ],
        "log_messages": []
    },
    "context": {
        "conversation_id": "7d7bced7-cdcf-4ba2-bb40-0e96afb80540",
        "system": {
            "dialog_stack": [
                {
                    "dialog_node": "Welcome"
                }
            ],
            "dialog_turn_counter": 1,
            "dialog_request_counter": 1,
            "_node_output_map": {
                "Welcome": [
                    0
                ]
            }
        },
        "get_input": "yes",
        "input_text": "",
        "shopping_cart": "list"
    }
}

**Comment by scottdangelo** [comment]
Definitely comes from the new version of the Python SDK.
Old version of message never called into `_convert_model()` which calls `_from_dict` and gets us the failure.

**Comment by scottdangelo** [comment]
And using the old SDK does not produce the error.
So...could pin the repo, but better to track down root cause.

**Comment by scottdangelo** [comment]
Working SDK has `latest_version = '2017-04-21'`

Broken SDK has no `latest_version`

**Comment by scottdangelo** [comment]
in the debugger, it is clear why this is failing:
```
(Pdb) print('conversation_id' in _dict)
False
(Pdb) print('context' in _dict)
True
```
But the structure of the json has not changed.
So....it is not clear why this would ever succeed.

**Comment by scottdangelo** [comment]
Here's the fix for the SDK
in conversation_v1.py:
```
        if 'conversation_id' in _dict['context']:
            args['conversation_id'] = _dict['context']['conversation_id']
            del xtra['context']['conversation_id']
        else:
            raise ValueError(
                'Required property \'conversation_id\' not present in Context JSON'
            )
        if 'system' in _dict['context']:
            args['system'] = SystemResponse._from_dict(_dict['context']['system'])
            del xtra['context']['system']
```

**Comment by scottdangelo** [comment]
I'll file a bug with the SDK team

**Comment by dhoffmann1979** [comment]
The fix doesn't work for me, i downgraded the sdk to 1.0.2 which is the last version working for me.

**Comment by stevemar** [comment]
@dhoffmann1979 did you try the SDK fix or https://github.com/IBM/watson-online-store/pull/135 ? We put up #135 to handle what looks like a breaking change in the SDK

**Comment by stevemar** [comment]
@dhoffmann1979 there is a fix for this issue in master now.
